version: "2"

linters:
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF1008" # don't suggest removing embedded field from selector https://staticcheck.dev/docs/checks#QF1008
        - "-ST1000" # Incorrect or missing package comment https://staticcheck.dev/docs/checks#ST1000
  exclusions:
    rules:
      - path: destination/common/data_types/
        text: "ST1003" # should not use underscores in package names (staticcheck)
      
       # QF1012: Usefmt.Fprintf instead of WriteString(fmt.Sprintf(...)) (staticcheck)
      - path: destination/cmd/start\.go
        text: "QF1012"
      - path: destination/db/rows\.go
        text: "QF1012"
      - path: destination/db/sql/sql\.go
        text: "QF1012"
