version: '3.8'
services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:${CLICKHOUSE_VERSION-24.1-alpine}'
    container_name: 'fivetran-destination-clickhouse-server'
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9004:9004'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - './.docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml'
      - './.docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml'
  destination:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: 'fivetran-destination-app'
    command: ./clickhouse_destination --replace-batch-size=2 --update-batch-size=2 --delete-batch-size=2
    ports:
      - '50052:50052'
